package org.ulinda.exceptions;

public enum ErrorCode {
    GENERAL_ERROR,
    INTERNAL_SERVER_ERROR,
    USER_ALREADY_EXISTS,
    CONTROLLER_VALIDATION_EXCEPTION,
    VALIDATION_EXCEPTION,
    OLD_PASSWORD_INCORRECT,
    USER_MUST_CHANGE_PASSWORD,
    INVALID_LOGIN_CREDENTIALS,
    RECORD_LINKED_TO_MODELS,
    MODEL_HAS_LINKED_RECORDS
}
